kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
    nodeSelector: {}
    strategy:
      type: Docker
    source:
      type: greeting-console
      git:
        uri: 'https://github.com/david970828/do400-greeting-console'
        ref: main
    output:
      to:
        kind: DockerImage
        name: quay.io/david970828/greeting-console
      pushSecret:
        name: quay-credentials